### ISSUE TITLE
Issue with newest version of vim ?

### ISSUE THREAD

**Issue by qwexvf** [mizukmb/otenki.vim#4]
Error detected while processing function otenki#callOtenkiInfo:
line    1:
E121: Undefined variable: g:otenki_cityname_data
E116: Invalid arguments for function get(a:, 1, g:otenki_cityname_data)
E15: Invalid expression: get(a:, 1, g:otenki_cityname_data)
line    3:
E121: Undefined variable: city
E116: Invalid arguments for function has_key(s:otenki_location_code_dict, city)
E15: Invalid expression: !has_key(s:otenki_location_code_dict, city)
line    7:
E121: Undefined variable: city
E15: Invalid expression: s:otenki_location_code_dict[city]
line    8:
E121: Undefined variable: city_code
E116: Invalid arguments for function otenki#getOtenkiInfo(city_code, a:day)
E15: Invalid expression: otenki#getOtenkiInfo(city_code, a:day)
line   10:
E121: Undefined variable: data
E15: Invalid expression: data.status == 500
line   13:
E121: Undefined variable: data
E15: Invalid expression: data.location . "の". data.date . "の天気は" . data.telop . "です"
0

Vim: 7.4
OS: OS X Elcapitan

Thanks.

**Comment by mizukmb** [comment]
Fixed bug. Thanks @xyzdevdox .

**Comment by qwexvf** [comment]
@mizukmb Thanks for your work, sounds like working as well. but without specifying the city i still getting the same error :(

i get it work with adding this line into my .vimrc
:let g:otenki_cityname_data = "shizuoka"

Thanks.

**Comment by mizukmb** [comment]
@xyzdevdox thanks for report. I fixed problem that undefined variable `g:otenki_cityname_data` .

Please update this and checkout to `mizukmb/bug-fix-for-default-city`. Moreover, make sure that was fixed bug on your PC.

**Comment by qwexvf** [comment]
@mizukmb Thanks for your job :+1: 

Everything fixed and works like a charm!!!!

**Comment by mizukmb** [comment]
@iamroar Thanks :laughing: 

I will merge `mizukmb/bug-fix-for-default-city` into `master`.
